### ISSUE TITLE
The iOS version is missing a feature of the android version

### ISSUE THREAD

**Issue by JakePayton** [dtrenz/BugShaker#26]
Device info and build info is included in the android email message body.  It would be nice to have this in iOS as well

**Comment by JakePayton** [comment]
Will be submitting a PR to address this today

**Comment by JakePayton** [comment]
https://github.com/dtrenz/BugShaker/pull/27 is meant to close this issue :)

**Comment by SlaunchaMan** [comment]
@dtrenz Can this be closed?

**Comment by dtrenz** [comment]
@SlaunchaMan Looks like. 👍
