### ISSUE TITLE
App crashes with appshaker included

### ISSUE THREAD

**Issue by pscadiz** [dtrenz/BugShaker#29]
Hi. I followed the readme for integration with my app and the app builds successfully. However, running the app and then shaking only crashes the app. Any ideas why?

Tested on iPhone 6 and iPad Air 2. Works fine on iPhone but crashes on iPad

**Comment by dtrenz** [comment]
I haven't seen this behavior. What is the crash, from the log?

**Comment by pscadiz** [comment]
Error is as follows. Seems to work properly on iPhone, but not on iPad:

<Error>: **\* Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x1556b8cb0>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
