### ISSUE TITLE
Mail Compose Viewer won't dismiss

### ISSUE THREAD

**Issue by JakePayton** [dtrenz/BugShaker#30]
This has been observed in builds in iOS 10.* and possibly other OS'

When the user taps the send button the MFMailComposeViewer is not dismissed (but an email is sent)

When the user taps the cancel button, an action sheet asking if the draft should be saved or discarded is shown.  If you select discard, the mail compose viewer seems to be dismissed...however, another one is persisting on screen.

It's as though there are multiple instances of the MFMailComposeViewer on screen.

I have not captured logs yet

**Comment by dtrenz** [comment]
This is fixed in the `swift-2.3` branch, which I plan to ship to CocoaPods as soon as I iron out some issues with tests.

**Comment by dtrenz** [comment]
This is now resolved in the latest release: 0.3.0 (#33)
